### ISSUE TITLE
Support Sitemap

### ISSUE THREAD

**Issue by YamiOdymel** [caris-events/tunalog#1]
讓 Tunalog 能夠自動產生 Sitemap 在 /sitemap.xml

**Comment by PichuChen** [comment]
我好像可以試試看

**Comment by YamiOdymel** [comment]
比想像中的應該有點小難度，要用 Gin Serve 一個虛擬的 sitemap.xml 路徑，
應該不會是真的檔案，而是讀取的時候讀取資料庫裡的 Posts 來產生對應的 XML 結構

**Comment by YamiOdymel** [comment]
可以試試看，後續有問題我再接手整理
