### ISSUE TITLE
Login with Username Results in 400 Error

### ISSUE THREAD

**Issue by meowrain** [caris-events/tunalog#13]
![image](https://github.com/user-attachments/assets/a6f0bd74-1914-4367-8136-34bb7e9548bd)
![image](https://github.com/user-attachments/assets/891431ed-a24e-420f-bd5e-806bd2db40c4)

測試環境：
WSL 
Arch Linux

**Comment by meowrain** [comment]
貌似只要填的不是郵箱就會報400錯誤碼
![image](https://github.com/user-attachments/assets/5ce3d507-eaa8-4f65-98ad-3b39b92a5599)

**Comment by YamiOdymel** [comment]
你說的對，也許我應該把 `type="text"` 改為 `type="email"`，
這樣瀏覽器就會跳出提醒該輸入的是電子信箱格式

![image](https://github.com/user-attachments/assets/c668397b-0dd4-477a-83b3-1ec0d9be23e6)
