### ISSUE TITLE
Inconsistent Login UI in Edge and Firefox

### ISSUE THREAD

**Issue by meowrain** [caris-events/tunalog#14]
> [Bug] CSS問題：在edge和firefox中樣式不一致

## FireFox

![image](https://github.com/user-attachments/assets/a40b355b-8c66-47d4-985d-4e44e7f84c70)

FireFox 版本
![image](https://github.com/user-attachments/assets/90d7e2b4-cd29-4f38-b0b8-07a86288afbd)

## Edge

![image](https://github.com/user-attachments/assets/42c6bfe4-6afc-442f-8bd0-c941b947d390)

Edge版本
![image](https://github.com/user-attachments/assets/f3d666af-5b6b-4ae6-85c1-bdc9d18d75c1)

**Comment by YamiOdymel** [comment]
我就說 Firefox 就像新 IE 一樣 😭
