### ISSUE TITLE
Improve 404 Pages

### ISSUE THREAD

**Issue by PichuChen** [caris-events/tunalog#15]
目前 (1.0.1) 如果是文章 （以及沒有權限的人輸入了私人文章的網址）的話找不到他會顯示的狀況 

`http://localhost:8123/post/hello-worldaa`
![スクリーンショット 2024-09-03 昼1 47 05](https://github.com/user-attachments/assets/162a3aa1-06de-4e7c-9447-4ef1c064fd58)

如果是一般性的網址的狀況 
`http://localhost:8123/hello-worldaa`
![スクリーンショット 2024-09-03 昼1 47 26](https://github.com/user-attachments/assets/accefbba-b0b2-46f4-80e2-881e23e59478)

也許有比較漂亮的畫面，或是可以自定義圖片？

**Comment by YamiOdymel** [comment]
目前的佈景主題有 `singular.html`（單篇文章） 跟 `index.html`（文章列表）的樣板檔案，也許該考慮新增一個 `404.html` 的樣板

**Comment by gglzc** [comment]
@YamiOdymel  不介意的話 可以assign給我 我下班如果有空可以幫忙做

**Comment by YamiOdymel** [comment]
好窩 😎 後續有問題我會再接手整理

造成文章顯示 404 程式碼在這段

https://github.com/caris-events/tunalog/blob/8994b275731b2ae6aa80cae568e6d40421e86204/handler/index_article.go#L129-L132

**Comment by YamiOdymel** [comment]
![image](https://github.com/user-attachments/assets/a625c5ee-4c50-4293-9a5d-00fbe41609d7)

這功能我發現比預期的還要有難度，所以就先暫時拒絕掉 @gglzc 的版本了。

主因是因為 404 有可能會在未知的路徑上造成，
會使 Tunalog 的相對路徑找不到怎麼回到根目錄的路徑。

原因是 Tunalog 不知道主站架在哪裡，也許未來要加上 BaseURL 的 Config
以避免有人把網站架在 `example.com/tunalog` 結果返回首頁卻回到 `example.com`，
不過這是之後要擔心的事了。
