### ISSUE TITLE
500 Error with Same Username, Different Email

### ISSUE THREAD

**Issue by PichuChen** [caris-events/tunalog#16]
當使用 tunalog 1.0.1 的時候，可以建立多個使用者
但是使用者的電子信箱地址的使用者名稱部份是唯一的，這樣會導致 HTTP 500 錯誤

# 重現方式

1. 先建立一個使用者，帳號是 `pichu@gmail.com`
![スクリーンショット 2024-09-03 昼2 07 23](https://github.com/user-attachments/assets/ae2d5857-9257-4b00-8c35-d8bfe6abe2c5)

2. 建立第二個使用者，帳號是 `pichu@whatever.com`

![スクリーンショット 2024-09-03 昼2 07 56](https://github.com/user-attachments/assets/8d14fcf6-bc30-4958-8bd0-b89168f387b9)

3. 點下建立後得到 500

![スクリーンショット 2024-09-03 昼2 08 07](https://github.com/user-attachments/assets/42b6e9bb-ffc6-4c96-9ed8-c73953d338fa)

<img width="679" alt="スクリーンショット 2024-09-03 昼2 08 29" src="https://github.com/user-attachments/assets/e4cb90ac-00af-4580-9c4a-98c7d6de6649">

# 可能原因

nickname 是 UNIQUE (唯一鍵) 
https://github.com/caris-events/tunalog/blob/45532a4d8fb6a92985a4f9acd3af4717071ee756/store/user.go#L12

而在新增使用者時自動生成 nickname 後並沒有考慮當 nickname 這個唯一鍵重複時的狀況。

# Workaround

1. 先修改舊有使用者的暱稱
![スクリーンショット 2024-09-03 昼2 15 11](https://github.com/user-attachments/assets/6849a8b7-620b-4762-84db-fa7d5c53aaf9)

2. 正常新增第二個使用者
3. 修改第二個使用者的暱稱，並且考慮是否要將舊有使用者的暱稱改回

# 建議修改方向
1.
在前端畫面增加 nickname, 並且透過 Javascript 在判斷 email 是否重複時同時自動產生 nickname
接著自動判斷 nickname 是否重複 （如果確實設計上就是希望 nickname 不得重複的話）
呼叫 `POST /admin/users` 的時候新增參數 nickname
新增失敗時如果原因是 email 重複或是 nickname 重複時確實回傳 4 開頭的錯誤訊息

2.
取消 nickname 不得重複 （會需要進行資料表 migration）

3.
發現 nickname 重複時再修改原有的 nickname 為 `nickname-{nonce}` 其中 nonce 可以是目前的時間毫秒值6位數字

**Comment by YamiOdymel** [comment]
我想應該會用第三種，例如：用 for 迴圈在名稱後面 +1 直到 Nickname 沒有重複為止，

Nickname 當初設為唯一鍵是因為有些下拉式選單只會顯示暱稱，
如果有重複的暱稱會分不清楚誰是誰

呼—還好不用 Migration，我最不會 Upgrade Migration ㄌ

![image](https://github.com/user-attachments/assets/249d97bc-3ec2-4d83-928c-e2403d8fcd4c)
