### ISSUE TITLE
Single line break doesn’t work in editor preview

### ISSUE THREAD

**Issue by lewis50093** [caris-events/tunalog#18]
在編輯文章及toggle priview功能 可正常顯示
![2](https://github.com/user-attachments/assets/5e50d362-e6e8-4dbb-8332-9f17ab9a57c0)
![3](https://github.com/user-attachments/assets/efb8f947-e8a2-46b2-9d0c-71da841533a6)

可是在外部瀏覽時換行符號會不見
<br> 則可以正常顯示
![1](https://github.com/user-attachments/assets/4b76e258-049c-45fa-931a-9bbcabd640f1)

**Comment by YamiOdymel** [comment]
Fixed b894d5d5f0534006a62b9799071ccfaa536463d6
