### ISSUE TITLE
Error creating a post with a title but without content

### ISSUE THREAD

**Issue by htmfilho** [caris-events/tunalog#23]
After pressing "Publish Post" with the title filled up but the content empty, a blank page and a log error message appear.

![Screenshot from 2024-09-04 18-48-17](https://github.com/user-attachments/assets/7aaba627-6848-4cab-8461-db4f7402eae0)

The content page is required, which is ok, but you may consider showing an error message instead of a blank page.

**Comment by YamiOdymel** [comment]
Post Create/Edit uses EasyMDE, which covers the `<textarea>`, so `<textarea required>` won't show the message on form submission.

Since WordPress allows blank posts, we might allow it too.
