### ISSUE TITLE
Appearance settings not getting saved

### ISSUE THREAD

**Issue by overflowy** [caris-events/tunalog#9]
https://github.com/user-attachments/assets/cb8e6561-b398-4912-80b3-b0825aa02f49

Platform: macos-arm64

**Comment by YamiOdymel** [comment]
You were supposed to press the 'Save Changes' button in the **Appearance & Content** section, but it looks like you pressed the one in **Injected Code** instead, sorry for the confusion.

![image](https://github.com/user-attachments/assets/a1aa6e1b-a288-44fe-b641-67d39681114c)

**Comment by overflowy** [comment]
I can't believe I didn't see it! I was a bit tired so that's maybe why I missed it. Regardless, thank you for this awesome app, it's incredibly well thought and nice.
